"""SQLAlchemy ORM Data Models for MindCare Therapy Agent.

Defines schemas for Role-Based Access Control (RBAC) User accounts and
multimodal conversational and stress telemetry ChatLogs.
"""

from datetime import datetime, timezone
from sqlalchemy import Column, DateTime, Float, ForeignKey, Integer, String
from sqlalchemy.orm import relationship

from database import Base


class UserRole:
    """Canonical User Roles for Role-Based Access Control (RBAC)."""
    USER: str = "user"
    ADMIN: str = "admin"
    SUPER_ADMIN: str = "super_admin"
    ALL_ROLES: list = [USER, ADMIN, SUPER_ADMIN]


class User(Base):
    """User account entity supporting Role-Based Access Control (RBAC).

    Attributes:
        id: Unique numeric identifier.
        username: Display username of the user.
        email: Unique user email address used for identification.
        password_hash: Secure salted password hash (e.g. bcrypt/argon2).
        role: RBAC permission role ('user', 'admin', or 'super_admin').
        chat_logs: Relationship linking all chat and telemetry turns initiated by this user.
    """

    __tablename__ = "users"

    id = Column(Integer, primary_key=True, index=True)
    username = Column(String, nullable=False)
    email = Column(String, unique=True, index=True, nullable=False)
    password_hash = Column(String, nullable=False)
    role = Column(String, default="user", nullable=False)
    avatar = Column(String, nullable=True)

    # 1-to-many relationship connecting user to their historical chat telemetry
    chat_logs = relationship("ChatLog", back_populates="user", cascade="all, delete-orphan")

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "username": self.username,
            "email": self.email,
            "role": self.role,
            "avatar": self.avatar,
        }

    def __repr__(self) -> str:
        return f"<User(id={self.id}, username='{self.username}', role='{self.role}')>"


class ChatLog(Base):
    """Multimodal conversational and biometric/stress telemetry record.

    Attributes:
        id: Unique numeric identifier for the chat turn.
        user_id: Foreign key reference associating log with a User entity.
        timestamp: UTC timestamp recording when turn occurred.
        user_message: Input text or transcribed speech provided by the user.
        ai_response: Empathy-first guided response generated by CBT Bot.
        detected_emotion: Fused multimodal emotion label (e.g. 'sad', 'happy', 'neutral').
        stress_score: Computed stress index (0.0 to 1.0).
        user: Back-reference to the owning User entity.
    """

    __tablename__ = "chat_logs"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(Integer, ForeignKey("users.id"), nullable=True, index=True)
    timestamp = Column(DateTime, default=lambda: datetime.now(timezone.utc), nullable=False)
    user_message = Column(String, nullable=True)
    ai_response = Column(String, nullable=True)
    detected_emotion = Column(String, nullable=True)
    stress_score = Column(Float, nullable=True)

    # Back-populates relationship with parent User
    user = relationship("User", back_populates="chat_logs")

    def to_dict(self) -> dict:
        return {
            "id": self.id,
            "user_id": self.user_id,
            "timestamp": self.timestamp.isoformat() if self.timestamp else None,
            "user_message": self.user_message,
            "ai_response": self.ai_response,
            "detected_emotion": self.detected_emotion,
            "stress_score": self.stress_score,
        }

    def __repr__(self) -> str:
        return f"<ChatLog(id={self.id}, user_id={self.user_id}, emotion='{self.detected_emotion}', stress={self.stress_score})>"
